export const peopleData = [
  {
    id: "p1",
    name: "Marina",
    age: 24,
    distance: 1.2,
    area: "Gonzaga, Santos",
    bio: "Fotografia, praia no fim da tarde e uma resenha tranquila sem pressa.",
    tags: ["Fotografia", "Praia", "Rolê tranquilo", "Santos"],
    online: true,
    calm: true,
    college: false,
    photo: "https://images.unsplash.com/photo-1496440737103-cd596325d314?auto=format&fit=crop&w=900&q=80",
    details: "Curte lugares abertos, música baixa e trocar ideia antes de combinar qualquer encontro.",
  },
  {
    id: "p2",
    name: "Caio",
    age: 27,
    distance: 2.4,
    area: "Boqueirão, Santos",
    bio: "Música, bar pequeno e gente que respeita o espaço dos outros.",
    tags: ["Música", "Rolê tranquilo", "Santos"],
    online: false,
    calm: true,
    college: false,
    photo: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=900&q=80",
    details: "Prefere roda pequena, localização aproximada e papo leve antes de entrar no grupo.",
  },
  {
    id: "p3",
    name: "Lia",
    age: 22,
    distance: 3.1,
    area: "Embaré, Santos",
    bio: "Faculdade, praia e descobrir gente da mesma vibe depois da aula.",
    tags: ["Faculdade", "Praia", "Música"],
    online: true,
    calm: true,
    college: true,
    photo: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
    details: "Está montando uma roda universitária com regras claras e convite por aprovação.",
  },
  {
    id: "p4",
    name: "Rafael",
    age: 31,
    distance: 1.8,
    area: "Ponta da Praia",
    bio: "Gosta de circular por eventos pequenos e chamar no papo antes de qualquer coisa.",
    tags: ["Eventos", "Santos", "Rolê tranquilo"],
    online: false,
    calm: true,
    college: false,
    photo: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=900&q=80",
    details: "Valoriza privacidade, respeito e localização exata só depois de confiança.",
  },
  {
    id: "p5",
    name: "Bianca",
    age: 26,
    distance: 4.6,
    area: "São Vicente",
    bio: "Praia, arte urbana e resenha em grupo com pessoas de boa.",
    tags: ["Praia", "Arte", "Rolê tranquilo"],
    online: true,
    calm: true,
    college: false,
    photo: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
    details: "Quer conhecer grupos perto da orla sem expor endereço nem rotina.",
  },
  {
    id: "p6",
    name: "Theo",
    age: 25,
    distance: 2.9,
    area: "Centro, Santos",
    bio: "Cinema, faculdade e papo bom em lugar seguro.",
    tags: ["Faculdade", "Cinema", "Santos"],
    online: true,
    calm: false,
    college: true,
    photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80",
    details: "Procura grupos abertos para conhecer gente nova na Baixada.",
  },
  {
    id: "p7",
    name: "Helena",
    age: 29,
    distance: 3.8,
    area: "Aparecida, Santos",
    bio: "Livros, café, caminhada e roda pequena com respeito.",
    tags: ["Café", "Rolê tranquilo", "Santos"],
    online: false,
    calm: true,
    college: false,
    photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80",
    details: "Prefere conversar primeiro e combinar apenas com grupos moderados.",
  },
  {
    id: "p8",
    name: "Nuno",
    age: 34,
    distance: 5.2,
    area: "Praia Grande",
    bio: "Organiza encontros adultos, sempre com regras e bom senso.",
    tags: ["Organizador", "Praia", "Segurança"],
    online: false,
    calm: false,
    college: false,
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=900&q=80",
    details: "Cria círculos com aprovação manual e aviso claro de comunidade.",
  },
  {
    id: "p9",
    name: "Sofia",
    age: 23,
    distance: 1.5,
    area: "Gonzaga, Santos",
    bio: "Música, faculdade e rolê depois da aula.",
    tags: ["Faculdade", "Música", "Santos"],
    online: true,
    calm: false,
    college: true,
    photo: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=900&q=80",
    details: "Quer achar gente por perto para trocar ideia sem pressão.",
  },
  {
    id: "p10",
    name: "Davi",
    age: 28,
    distance: 3.4,
    area: "José Menino",
    bio: "Curte orla, foto analógica e grupo pequeno no fim de tarde.",
    tags: ["Fotografia", "Praia", "Rolê tranquilo"],
    online: false,
    calm: true,
    college: false,
    photo: "https://images.unsplash.com/photo-1531891437562-4301cf35b7e4?auto=format&fit=crop&w=900&q=80",
    details: "Entra só em rodas com local aproximado e criador identificado.",
  },
  {
    id: "p11",
    name: "Malu",
    age: 21,
    distance: 2.2,
    area: "Vila Mathias",
    bio: "Faculdade, playlists e resenha leve com gente educada.",
    tags: ["Faculdade", "Música", "Rolê tranquilo"],
    online: true,
    calm: true,
    college: true,
    photo: "https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?auto=format&fit=crop&w=900&q=80",
    details: "Gosta de grupos universitários com regras simples e respeito.",
  },
  {
    id: "p12",
    name: "André",
    age: 33,
    distance: 6.1,
    area: "Guarujá",
    bio: "Praia, conversa adulta e encontro só com consentimento claro.",
    tags: ["Praia", "Segurança", "Santos"],
    online: false,
    calm: true,
    college: false,
    photo: "https://images.unsplash.com/photo-1530268729831-4b0b9e170218?auto=format&fit=crop&w=900&q=80",
    details: "Usa o app para conhecer círculos próximos sem revelar endereço.",
  },
];

export const groupsData = [
  {
    id: "g1",
    name: "Sunset Gonzaga",
    distance: 1.1,
    members: 18,
    status: "Aberto",
    area: "Gonzaga",
    tags: ["Praia", "Hoje", "Aberto"],
    open: true,
    today: true,
    university: false,
    description: "Fim de tarde na orla, roda pequena e local exato só depois da aprovação.",
    rules: ["Adultos apenas", "Respeitar leis locais", "Não expor localização do grupo"],
    photo: "https://images.unsplash.com/photo-1506869640319-fe1a24fd76dc?auto=format&fit=crop&w=1200&q=80",
    x: 24,
    y: 36,
  },
  {
    id: "g2",
    name: "Circle Universitário",
    distance: 2.6,
    members: 24,
    status: "Fechado",
    area: "Vila Mathias",
    tags: ["Universitários", "Faculdade", "Hoje"],
    open: false,
    today: true,
    university: true,
    description: "Grupo para trocar ideia depois da aula, com entrada moderada.",
    rules: ["Pedir entrada", "Criador libera local", "Sem venda ou compra"],
    photo: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=1200&q=80",
    x: 62,
    y: 42,
  },
  {
    id: "g3",
    name: "Rolê Baixada",
    distance: 3.7,
    members: 31,
    status: "Aberto",
    area: "Boqueirão",
    tags: ["Mais membros", "Aberto", "Santos"],
    open: true,
    today: false,
    university: false,
    description: "Círculo maior para achar uma resenha tranquila na Baixada.",
    rules: ["Sem pressão", "Local aproximado", "Denuncie comportamento ruim"],
    photo: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&q=80",
    x: 48,
    y: 68,
  },
  {
    id: "g4",
    name: "Praia & Resenha",
    distance: 0.9,
    members: 14,
    status: "Aberto",
    area: "Embaré",
    tags: ["Praia", "Aberto", "Rolê tranquilo"],
    open: true,
    today: false,
    university: false,
    description: "Papo leve perto da praia, sempre com localização aproximada.",
    rules: ["Chegar com respeito", "Não compartilhar endereço", "Apenas adultos"],
    photo: "https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?auto=format&fit=crop&w=1200&q=80",
    x: 34,
    y: 24,
  },
  {
    id: "g5",
    name: "Depois da Aula",
    distance: 2.1,
    members: 16,
    status: "Aberto",
    area: "Centro",
    tags: ["Universitários", "Faculdade", "Hoje"],
    open: true,
    today: true,
    university: true,
    description: "Roda universitária para conversar depois da aula sem bagunça.",
    rules: ["Convite por pedido", "Respeitar limites", "Nada ilegal"],
    photo: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80",
    x: 72,
    y: 58,
  },
  {
    id: "g6",
    name: "Jardim da Orla",
    distance: 4.0,
    members: 9,
    status: "Fechado",
    area: "Ponta da Praia",
    tags: ["Praia", "Até 4 km", "Fechado"],
    open: false,
    today: false,
    university: false,
    description: "Grupo pequeno para quem prefere roda mais reservada.",
    rules: ["Criador aprova", "Local exato privado", "Conversa antes de entrar"],
    photo: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80",
    x: 18,
    y: 72,
  },
  {
    id: "g7",
    name: "Café e Papo",
    distance: 3.3,
    members: 12,
    status: "Aberto",
    area: "Aparecida",
    tags: ["Hoje", "Rolê tranquilo", "Aberto"],
    open: true,
    today: true,
    university: false,
    description: "Café, conversa e uma roda adulta sem exposição.",
    rules: ["Uso responsável", "Sem checkout", "Sem venda de substâncias"],
    photo: "https://images.unsplash.com/photo-1511988617509-a57c8a288659?auto=format&fit=crop&w=1200&q=80",
    x: 58,
    y: 26,
  },
  {
    id: "g8",
    name: "Trago com Respeito",
    distance: 5.8,
    members: 20,
    status: "Fechado",
    area: "São Vicente",
    tags: ["Segurança", "Mais membros", "Fechado"],
    open: false,
    today: false,
    university: false,
    description: "Comunidade adulta com moderação, regras e privacidade.",
    rules: ["Compartilhar local só com confiança", "Denúncias revisadas", "Respeitar leis locais"],
    photo: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=1200&q=80",
    x: 82,
    y: 76,
  },
];

export const productsData = [
  { id: "a1", name: "Seda Natural King Size", category: "Sedas", price: "R$ 14,90", popular: true, description: "Papel de queima lenta para uso adulto e legal.", tags: ["natural", "fina"], image: "https://images.unsplash.com/photo-1607344645866-009c320f1f37?auto=format&fit=crop&w=900&q=80" },
  { id: "a2", name: "Seda Brown Slim", category: "Sedas", price: "R$ 12,90", popular: false, description: "Seda marrom com visual discreto e textura leve.", tags: ["brown", "slim"], image: "https://images.unsplash.com/photo-1607344645866-009c320f1f37?auto=format&fit=crop&w=900&q=70" },
  { id: "a3", name: "Piteira de Vidro Curta", category: "Piteiras", price: "R$ 32,00", popular: true, description: "Peça reutilizável com acabamento limpo.", tags: ["vidro", "reutilizável"], image: "https://images.unsplash.com/photo-1602526432604-029a709e131c?auto=format&fit=crop&w=900&q=80" },
  { id: "a4", name: "Piteira Papel Longa", category: "Piteiras", price: "R$ 9,90", popular: false, description: "Formato firme para montagem organizada.", tags: ["papel", "longa"], image: "https://images.unsplash.com/photo-1610470801073-3dd0d43c4f84?auto=format&fit=crop&w=900&q=80" },
  { id: "a5", name: "Dichavador Alumínio Fosco", category: "Dichavadores", price: "R$ 79,90", popular: true, description: "Acessório metálico para organização visual do kit.", tags: ["alumínio", "fosco"], image: "https://images.unsplash.com/photo-1616627561839-074385245ff6?auto=format&fit=crop&w=900&q=80" },
  { id: "a6", name: "Dichavador Compacto Verde", category: "Dichavadores", price: "R$ 49,90", popular: false, description: "Peça compacta com cor discreta.", tags: ["compacto", "verde"], image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=900&q=80" },
  { id: "a7", name: "Bandeja Metal Grafite", category: "Bandejas", price: "R$ 59,90", popular: true, description: "Superfície estável para organizar acessórios adultos.", tags: ["metal", "mesa"], image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80" },
  { id: "a8", name: "Bandeja Madeira Clara", category: "Bandejas", price: "R$ 69,90", popular: false, description: "Visual natural para deixar o kit organizado.", tags: ["madeira", "organização"], image: "https://images.unsplash.com/photo-1602872030490-4a484a7b3ba6?auto=format&fit=crop&w=900&q=80" },
  { id: "a9", name: "Cuia Cerâmica Areia", category: "Cuia", price: "R$ 44,90", popular: true, description: "Peça de apoio com acabamento neutro.", tags: ["cerâmica", "apoio"], image: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=900&q=80" },
  { id: "a10", name: "Cuia Pedra Escura", category: "Cuia", price: "R$ 54,90", popular: false, description: "Acessório de mesa com presença mineral.", tags: ["pedra", "escura"], image: "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=900&q=80" },
  { id: "a11", name: "Isqueiro Metal Escovado", category: "Isqueiros", price: "R$ 39,90", popular: true, description: "Corpo metálico resistente e discreto.", tags: ["metal", "bolso"], image: "https://images.unsplash.com/photo-1609951651556-5334e2706168?auto=format&fit=crop&w=900&q=80" },
  { id: "a12", name: "Isqueiro Mini Preto", category: "Isqueiros", price: "R$ 19,90", popular: false, description: "Pequeno, simples e fácil de carregar.", tags: ["mini", "preto"], image: "https://images.unsplash.com/photo-1609951651556-5334e2706168?auto=format&fit=crop&w=900&q=70" },
  { id: "a13", name: "Kit Bolso Essencial", category: "Kits", price: "R$ 119,90", popular: true, description: "Conjunto visual de acessórios legais para adultos.", tags: ["kit", "bolso"], image: "https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=900&q=80" },
  { id: "a14", name: "Kit Mesa Organizada", category: "Kits", price: "R$ 149,90", popular: false, description: "Seleção mockada para manter tudo em ordem.", tags: ["mesa", "organização"], image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=900&q=80" },
  { id: "a15", name: "Seda Ultra Fina", category: "Sedas", price: "R$ 16,90", popular: true, description: "Opção leve para quem prefere montagem discreta.", tags: ["ultra fina", "discreta"], image: "https://images.unsplash.com/photo-1517705008128-361805f42e86?auto=format&fit=crop&w=900&q=80" },
  { id: "a16", name: "Piteira Cerâmica Off", category: "Piteiras", price: "R$ 42,90", popular: false, description: "Acabamento cerâmico em tom claro, pensado para reuso.", tags: ["cerâmica", "reuso"], image: "https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=900&q=80" },
  { id: "a17", name: "Dichavador Texturizado", category: "Dichavadores", price: "R$ 89,90", popular: true, description: "Visual mais robusto para compor um kit adulto.", tags: ["textura", "robusto"], image: "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=900&q=80" },
  { id: "a18", name: "Bandeja Compacta Areia", category: "Bandejas", price: "R$ 52,90", popular: false, description: "Bandeja pequena para uso visual em mesa ou bancada.", tags: ["compacta", "areia"], image: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=900&q=80" },
  { id: "a19", name: "Isqueiro Clássico Creme", category: "Isqueiros", price: "R$ 24,90", popular: false, description: "Modelo simples para compor a vitrine sem checkout.", tags: ["clássico", "creme"], image: "https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=900&q=80" },
  { id: "a20", name: "Kit Praia & Resenha", category: "Kits", price: "R$ 169,90", popular: true, description: "Conjunto visual para rotina adulta, organizado e responsável.", tags: ["praia", "kit"], image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=80" },
];
